function dividir(num1,num2){
	try {
	if(num2 == 0)
		throw "Divisão por zero não é permitida";
		return n1 / n2;
	}catch(err){
		console.log(err);
		return null
	}
}

let num1 = 10;
let num2 = 0;
resultado = dividir(num1,num2);
console.log(resultado);

// COLOCO TODAS AS EXECUÇÕES DA FUNÇÃO NO TRY. CASO DÊ ALGUM ERRO NESSA EXECUÇÃO, VAI CAIR NO CATCH
